

build:; forge build

deploy-goerli:; forge script script/Mchango.s.sol.s.sol:DeployMchango --rpc-url $(RPC_URL) --private-key $(PRIVATE_KEY) --broadcast 
deploy-mumbai:; forge script script/Mchango.s.sol.s.sol:DeployMchango --rpc-url $(MUMBAI_RPC_URL) --private-key $(MUMBAI_PRIVATE_KEY)  --broadcast

run-test:; forge test --mp test/unit/MchangoTest.s.sol -vv