

build:; forge build

deploy-goerli:; forge script script/FundMe.s.sol:FundMeDeploy --rpc-url $(RPC_URL) --private-key $(PRIVATE_KEY) --broadcast 

run-test:; forge test --mp test/unit/MchangoTest.s.sol -vv